apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxcloud
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fluxcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: fluxcloud
    spec:
      securityContext:
        runAsUser: 999
      containers:
      - name: fluxcloud
        image: justinbarrick/fluxcloud:v0.3.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3032
        env:
        - name: SLACK_URL
          valueFrom:
            secretKeyRef:
              name: fluxcloud
              value: slack_url
        - name: SLACK_CHANNEL
          value: '#flux'
        - name: SLACK_USERNAME
          value: 'Flux'
        - name: SLACK_ICON_EMOJI
          value: ':weave:'
        - name: GITHUB_URL
          value: 'https://github.com/anthonyneto/k8s-fun'
        - name: LISTEN_ADDRESS
          value: ':3032'
