apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: ingress
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~v0.
spec:
  releaseName: metallb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metallb
    version: 0.12.0
  values:
    configInline:
        address-pools:
        - name: default
          protocol: layer2
          addresses:
          - 192.168.5.200-192.168.5.220
